server:
 port: 8081

spring:
 application:
  name: icu-service

 datasource:
  username: sa
  password: 
  url: jdbc:h2:mem:testdb
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
 h2:
  console.enabled: true

eureka:
 client:
  service-url: 
   default-zone: http://localhost:8761/eureka
  fetch-registry: true
  register-with-eureka: true